[package]
name = "linkerd-server-policy"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
linkerd-authz = { path = "../authz" }
linkerd-http-routes = { path = "../http-routes" }
