type-complexity-threshold = 500
disallowed-methods = [
    # Mutating environment variables in a multi-threaded context can
    # cause data races.
    # see https://github.com/rust-lang/rust/issues/90308 for details.
    "std::env::set_var",
    "std::env::remove_var",

    # Use parking_lot instead.
    "std::sync::Mutex",
    "std::sync::RwLock",
]
