[package]
name = "linkerd-authz"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
ipnet = "2"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
