[package]
name = "linkerd-grpc-route"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
proto = ["linkerd2-proxy-api", "linkerd-http-route/proto"]

[dependencies]
http = "0.2"
linkerd2-proxy-api = { version = "0.5", features = ["grpc-route"], optional = true }
linkerd-http-route = { path = "../http-route" }
thiserror = "1"

[dev-dependencies]
maplit = "1"
