name: devcontainer

# When a pull request is opened that changes the Devcontainer configuration,
# ensure that the container continues to build properly.
on: [pull_request]

permissions:
  contents: read

jobs:
  changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: tj-actions/changed-files@205450238e81d3da0e0ec2d776f58c12846fddfb
        id: changed-files
        with:
          files: |
            rust-toolchain
            .devcontainer/*
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed == 'true' && 'true'  || '' }}

  build:
    needs: [changes]
    if: needs.changes.outputs.changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: docker build .devcontainer

  devcontainer-image:
    needs: [changes]
    if: needs.changes.outputs.changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install jq
      - run: |
          image=$(sed -E '/^\s*\/\/.*/d' .devcontainer/devcontainer.json |jq -Mr .image)
          if [ "$image" == "null" ]; then
            echo "::error file=.devcontainer/devcontainer.json::Missing image"
            exit 1
          fi
          if ! docker pull "$image" ; then
            echo "::error file=.devcontainer/devcontainer.json::Unable to pull image: $image"
            exit 1
          fi
