name: docker

on: [pull_request]

permissions:
  contents: read

jobs:
  changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: tj-actions/changed-files@205450238e81d3da0e0ec2d776f58c12846fddfb
        id: changed-files
        with:
          files: |
            Dockerfile
            rust-toolchain
            .github/workflows/docker.yml
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed == 'true' && 'true'  || '' }}

  build:
    needs: [changes]
    if: needs.changes.outputs.changed
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: just docker
