name: fuzzers

on: [pull_request]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

permissions:
  contents: read

jobs:
  changes:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.60.0-bullseye
    steps:
      - run: apt update && apt install -y jo
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: tj-actions/changed-files@205450238e81d3da0e0ec2d776f58c12846fddfb
        id: changed-files
        with:
          files: |
            linkerd/addr/**
            linkerd/app/inbound/**
            linkerd/dns/**
            linkerd/proxy/http/**
            linkerd/tls/**
            linkerd/transport-header/**
            .github/workflows/fuzzers.yml
      - name: list changed crates
        id: list-changed
        shell: bash
        run: |
          files="${{ steps.changed-files.outputs.all_changed_files }}"
          # Find the nearest fuzzer crate, or nothing.
          find_fuzz_dir() {
            d=$(dirname "$1")
            if [ "$d" = . ]; then
              return
            elif [ -d "$d" ] && [[ "$d" = */fuzz ]]; then
              echo "$d"
            elif [ -f "$d/fuzz/Cargo.toml" ]; then
              echo "$d/fuzz"
            else
              find_fuzz_dir "$d"
            fi
          }
          list_dirs() {
            dirs=""
            for file in $(echo $*) ; do
              if [ "$file" = .github/workflows/fuzzers.yml ]; then
                dirs=$(find . -type d -name fuzz)
                break
              fi
              d=$(find_fuzz_dir "$file")
              if [ -n "$d" ]; then
                if [ -z "$dirs" ]; then
                  dirs="$d"
                else
                  dirs="$dirs $d"
                fi
              fi
            done
            echo "${dirs}" | tr ' ' "\n" | sort -u
          }
          dirs=$(list_dirs $files)
          echo "$dirs"
          echo "::set-output name=dirs::$(echo "$dirs" | jo -a)"
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed == 'true' && 'true'  || '' }}
      dirs: ${{ steps.list-changed.outputs.dirs }}

  # Build fuzzers for any changed crates.
  build:
    needs: [changes]
    if: needs.changes.outputs.changed
    timeout-minutes: 40
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.60.0-bullseye
    strategy:
      matrix:
        dir: ${{ fromJson(needs.changes.outputs.dirs) }}
    steps:
      - run: rustup toolchain add nightly
      - run: cargo install cargo-fuzz
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - working-directory: ${{matrix.dir}}
        run: cargo +nightly fetch
      - working-directory: ${{matrix.dir}}
        run: cargo +nightly fuzz build
