# Each job should typically run in under 5 minutes.
name: lint

permissions:
  contents: read

on: [pull_request]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: tj-actions/changed-files@205450238e81d3da0e0ec2d776f58c12846fddfb
        id: changed-files
        with:
          files: |
            rust-toolchain
            **/*.rs
            .github/workflows/lint.yml
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed == 'true' && 'true' || '' }}

  clippy:
    needs: [changes]
    if: needs.changes.outputs.changed
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.60.0-bullseye
    steps:
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb
      - uses: olix0r/cargo-action-fmt@ee1ef42932e44794821dab57ef1bf7a73df8b21f
      - run: rustup component add clippy
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/install-protoc
      - run: just fetch
      - run: just clippy --exclude=linkerd-meshtls-boring

  fmt:
    needs: [changes]
    if: needs.changes.outputs.changed
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.60.0-bullseye
    steps:
      - run: rustup component add rustfmt
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: just check-fmt

  docs:
    needs: [changes]
    if: needs.changes.outputs.changed
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.60.0-bullseye
    steps:
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb
      - uses: olix0r/cargo-action-fmt@ee1ef42932e44794821dab57ef1bf7a73df8b21f
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: just fetch
      - run: just doc --exclude=linkerd-meshtls-boring

